### **Array Manipulation**

In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(3,4))

In [3]:
arr

array([[8, 6, 6, 5],
       [4, 8, 3, 3],
       [6, 8, 7, 7]], dtype=int32)

In [5]:
arr.reshape(6,2)

array([[8, 6],
       [6, 5],
       [4, 8],
       [3, 3],
       [6, 8],
       [7, 7]], dtype=int32)

In [6]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [7]:
arr.T

array([[8, 4, 6],
       [6, 8, 8],
       [6, 3, 7],
       [5, 3, 7]], dtype=int32)

In [9]:
arr.flatten()#convert dimension

array([8, 6, 6, 5, 4, 8, 3, 3, 6, 8, 7, 7], dtype=int32)

In [10]:
arr1=np.array([1,2,3,3,4])

In [11]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [15]:
arr

array([[8, 6, 6, 5],
       [4, 8, 3, 3],
       [6, 8, 7, 7]], dtype=int32)

In [16]:
np.squeeze(arr)

array([[8, 6, 6, 5],
       [4, 8, 3, 3],
       [6, 8, 7, 7]], dtype=int32)

In [17]:
data=np.array([[1],[2],[3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [21]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [22]:
arr1

array([1, 2, 3, 3, 4])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

## **Binary operation**

In [24]:
arr1=np.random.randint(1,10,(3,4))

In [25]:
arr2=np.random.randint(1,10,(3,4))

In [28]:
arr1+arr2


array([[ 9,  5, 11,  9],
       [ 6,  7,  9,  5],
       [16, 12,  9,  6]], dtype=int32)

In [29]:
arr1*arr2

array([[ 8,  4, 30,  8],
       [ 5,  6, 20,  6],
       [63, 35, 18,  5]], dtype=int32)

In [30]:
arr1/arr2

array([[0.125     , 4.        , 0.83333333, 0.125     ],
       [0.2       , 0.16666667, 1.25      , 0.66666667],
       [0.77777778, 0.71428571, 2.        , 0.2       ]])

In [31]:
arr1-arr2

array([[-7,  3, -1, -7],
       [-4, -5,  1, -1],
       [-2, -2,  3, -4]], dtype=int32)

In [32]:
arr1%arr2

array([[1, 0, 5, 1],
       [1, 1, 1, 2],
       [7, 5, 0, 1]], dtype=int32)

In [33]:
arr1**arr2

array([[       1,        4,    15625,        1],
       [       1,        1,      625,        8],
       [40353607,    78125,      216,        1]], dtype=int32)

In [34]:
arr1&arr2

array([[0, 0, 4, 0],
       [1, 0, 4, 2],
       [1, 5, 2, 1]], dtype=int32)

In [35]:
arr|arr2

array([[ 8,  7,  6, 13],
       [ 5, 14,  7,  3],
       [15, 15,  7,  7]], dtype=int32)

In [36]:
~arr1

array([[-2, -5, -6, -2],
       [-2, -2, -6, -3],
       [-8, -6, -7, -2]], dtype=int32)

In [37]:
arr1>arr2

array([[False,  True, False, False],
       [False, False,  True, False],
       [False, False,  True, False]])

## ***String function***

In [40]:
arr=np.array(['asma','latif'])

In [42]:
np.char.upper(arr)

array(['ASMA', 'LATIF'], dtype='<U5')

In [43]:
np.char.title(arr)

array(['Asma', 'Latif'], dtype='<U5')

In [44]:
np.char.capitalize(arr)

array(['Asma', 'Latif'], dtype='<U5')

## **Mathematical function**

In [45]:
arr1

array([[1, 4, 5, 1],
       [1, 1, 5, 2],
       [7, 5, 6, 1]], dtype=int32)

In [46]:
np.sin(arr1)

array([[ 0.84147098, -0.7568025 , -0.95892427,  0.84147098],
       [ 0.84147098,  0.84147098, -0.95892427,  0.90929743],
       [ 0.6569866 , -0.95892427, -0.2794155 ,  0.84147098]])

In [47]:
np.cos(arr1)

array([[ 0.54030231, -0.65364362,  0.28366219,  0.54030231],
       [ 0.54030231,  0.54030231,  0.28366219, -0.41614684],
       [ 0.75390225,  0.28366219,  0.96017029,  0.54030231]])

In [48]:
np.tan(arr1)

array([[ 1.55740772,  1.15782128, -3.38051501,  1.55740772],
       [ 1.55740772,  1.55740772, -3.38051501, -2.18503986],
       [ 0.87144798, -3.38051501, -0.29100619,  1.55740772]])

In [49]:
np.tanh(arr1)

array([[0.76159416, 0.9993293 , 0.9999092 , 0.76159416],
       [0.76159416, 0.76159416, 0.9999092 , 0.96402758],
       [0.99999834, 0.9999092 , 0.99998771, 0.76159416]])

In [50]:
np.log10(arr1)

array([[0.        , 0.60205999, 0.69897   , 0.        ],
       [0.        , 0.        , 0.69897   , 0.30103   ],
       [0.84509804, 0.69897   , 0.77815125, 0.        ]])

In [51]:
np.exp(arr1)

array([[   2.71828183,   54.59815003,  148.4131591 ,    2.71828183],
       [   2.71828183,    2.71828183,  148.4131591 ,    7.3890561 ],
       [1096.63315843,  148.4131591 ,  403.42879349,    2.71828183]])

In [52]:
np.sqrt(arr1)

array([[1.        , 2.        , 2.23606798, 1.        ],
       [1.        , 1.        , 2.23606798, 1.41421356],
       [2.64575131, 2.23606798, 2.44948974, 1.        ]])

In [54]:
np.power(arr1,2)

array([[ 1, 16, 25,  1],
       [ 1,  1, 25,  4],
       [49, 25, 36,  1]], dtype=int32)

In [55]:
np.mean(arr1)

np.float64(3.25)

In [57]:
np.median(arr1)

np.float64(3.0)

In [58]:
np.std(arr1)

np.float64(2.203217344400381)

In [59]:
np.var(arr1)

np.float64(4.854166666666667)

In [60]:
np.min(arr1)

np.int32(1)

In [61]:
np.max(arr1)

np.int32(7)

#### **sort,search and counting function**

In [62]:
arr=np.array([4,3,6,7,2,3,1])

In [63]:
np.sort(arr)

array([1, 2, 3, 3, 4, 6, 7])

In [64]:
np.searchsorted(arr,34)

np.int64(7)

In [66]:
ar1=np.array([0,4,5,6,7,9,3,44,0,0,0])

In [67]:
np.count_nonzero(ar1)

np.int64(7)

In [70]:
np.where(ar1>6)

(array([4, 5, 7]),)

In [69]:
np.extract(ar1>6,ar1)

array([ 7,  9, 44])

### **Bite swapping**

In [71]:
ar1.byteswap()

array([                  0,  288230376151711744,  360287970189639680,
        432345564227567616,  504403158265495552,  648518346341351424,
        216172782113783808, 3170534137668829184,                   0,
                         0,                   0])

### **copies &views**

In [72]:
ar1

array([ 0,  4,  5,  6,  7,  9,  3, 44,  0,  0,  0])

In [73]:
a=np.copy(ar1)

In [75]:
b=ar1.view()

In [76]:
b

array([ 0,  4,  5,  6,  7,  9,  3, 44,  0,  0,  0])

In [77]:
a

array([ 0,  4,  5,  6,  7,  9,  3, 44,  0,  0,  0])

### **Matrix Library**

In [78]:
import numpy.matlib as nm

In [79]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [80]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [81]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### **Linear Algebra**

In [ ]:
ar1=np.random.randint([[2,3],[4,5]])

In [83]:
ar2=np.random.randint([[5,3],[2,5]])

In [84]:
np.dot(ar1,ar2)

array([[1, 0],
       [1, 0]], dtype=int32)

In [85]:
ar1@ar2

array([[1, 0],
       [1, 0]], dtype=int32)