### <i>NumPy Basics</i>

<small><i>Creating Arrays</i></small>

<small><i>Using `np.array()`</i></small>

<small><i>Using `np.asarray()`</i></small>

<small><i>Using `np.asanyarray()`</i></small>

<small><i>Matrix and Array Conversion</i></small>

<small><i>Copy vs Reference</i></small>

<small><i>Shallow Copy</i></small>

<small><i>Deep Copy using `np.copy()`</i></small>

<small><i>Creating Arrays with `np.fromfunction()`</i></small>

<small><i>Creating Arrays with `np.fromiter()`</i></small>

<small><i>Creating Arrays with `np.fromstring()`</i></small>

<small><i>Array Properties (`ndim`, `size`, `shape`, `dtype`)</i></small>

<small><i>Creating Arrays with `np.arange()`</i></small>

<small><i>Creating Arrays with `np.linspace()`</i></small>

<small><i>Summary</i></small>

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4]

In [ ]:
ar=np.array(l)

In [ ]:
ar

array([1, 2, 3, 4])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
a=[1,2,3,4]

In [ ]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [ ]:
b=np.matrix(l)

In [ ]:
b

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [ ]:
a=np.array(l)

In [ ]:
c=a

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
c[0]=100

In [ ]:
c

array([100,   2,   3,   4])

In [ ]:
a

array([100,   2,   3,   4])

In [ ]:
d=np.copy(a)

In [ ]:
d

array([100,   2,   3,   4])

In [ ]:
a[1]=400

In [ ]:
a

array([100, 400,   3,   4])

In [ ]:
d

array([100,   2,   3,   4])

In [ ]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterable=(i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
arr = np.fromstring("234 234", dtype=int, sep=' ')
print(arr)

[234 234]


In [ ]:
arr.ndim

1

In [ ]:
arr.size

2

In [ ]:
arr.shape

(2,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
ar22=np.array([(1.4,45,66),(25,45,33)])

In [ ]:
ar22

array([[ 1.4, 45. , 66. ],
       [25. , 45. , 33. ]])

In [ ]:
ar22.dtype

dtype('float64')

In [ ]:
np.arange(1.2,9.0)

array([1.2, 2.2, 3.2, 4.2, 5.2, 6.2, 7.2, 8.2])

In [ ]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a=[1,2,3,4]

In [10]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [11]:
b=np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a=np.array(l)

In [16]:
c=a

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c

array([1, 2, 3, 4])

In [19]:
c[0]=100

In [20]:
c

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
d=np.copy(a)

In [23]:
d

array([100,   2,   3,   4])

In [26]:
a[1]=400

In [27]:
a

array([100, 400,   3,   4])

In [28]:
d

array([100,   2,   3,   4])

In [29]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
iterable=(i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
arr = np.fromstring("234 234", dtype=int, sep=' ')
print(arr)

[234 234]


In [36]:
arr.ndim

1

In [37]:
arr.size

2

In [38]:
arr.shape

(2,)

In [39]:
arr.dtype

dtype('int64')

In [40]:
ar22=np.array([(1.4,45,66),(25,45,33)])

In [41]:
ar22

array([[ 1.4, 45. , 66. ],
       [25. , 45. , 33. ]])

In [42]:
ar22.dtype

dtype('float64')

In [44]:
np.arange(1.2,9.0)

array([1.2, 2.2, 3.2, 4.2, 5.2, 6.2, 7.2, 8.2])

In [45]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [46]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])