## *NUMPY*

In [1]:
import numpy as np


##### ***Difference between array and list**

In [30]:
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [31]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


#### **DATA TYPES**
#### **Int32,Int64,Int8,Float32,Float64,bool**

In [20]:
a=np.array([1,2,3],np.int8)
b=np.array([1.5,2.8,3.9],np.float32)
c=np.array([True,False],np.bool)
print(a.dtype)
print(b.dtype)
print(c.dtype)

int8
float32
bool


In [21]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

1
4
1


In [14]:
myarr=np.array([[3,6,32,7]],np.int64)

In [15]:
myarr

array([[ 3,  6, 32,  7]])

In [9]:
arr=np.array([3,4,5,99999],np.int8)

OverflowError: Python integer 99999 out of bounds for int8

In [16]:
myarr[0]

array([ 3,  6, 32,  7])

In [17]:
myarr.shape

(1, 4)

In [18]:
myarr.dtype

dtype('int64')

In [19]:
myarr.itemsize

8

### ***Array creation:COnversion from other python structures***

In [23]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
listarray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
listarray.dtype

dtype('int64')

In [26]:
listarray.shape

(3, 3)

In [27]:
listarray.size

9

In [28]:
np.array({34,23,23})

array({34, 23}, dtype=object)